app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog'))
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('product/', views.product, name='product'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('deliever/', views.deliever, name='deliever')
]

goods/models.py
from tabnanny import verbose
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="სახელი")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "კატეგორია"
        verbose_name_plural = "კატეგორიები"

    def __str__(self) -> str:
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="სახელი")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="აღწერა")
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="გამოსახულება")
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name="ფასი")
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name="ფასდაკლება % -ში")
    quantity = models.PositiveIntegerField(default=0, verbose_name='რაოდენობა')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name="კატეგორია")
    class Meta:
        db_table = "product"
        verbose_name = "პროდუქტი"
        verbose_name_plural = "პროდუქტები"

    def __str__(self) -> str:
        return f'{self.name} რაოდენობა - {self.quantity}'
    
    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price  - self.price * self.discount / 100, 2)
        else:
            return self.price

goods/views.py
from django.shortcuts import render

from goods.models import Products


def catalog(request):

    goods = Products.objects.all()

    context = {
        "title": "Home - კატალოგი",
        "goods": goods,
    }
    return render(request, "goods/catalog.html", context)


def product(request):
    return render(request, "goods/product.html")

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from goods.models import Categories

def index(request):

    
    context: dict[str, str] = {
        "title": "Home - მთავარი",
        "content": "მაღაზია HOME",
}

    return render(request, 'main/index.html', context)

def about(request):
    context: dict[str, str] = {
        "title": "Home - ჩვენზე",
        "content": "ჩვენზე",
        "text_on_page": "ჩვენ მზად ვართ გავხადოთ თქვენი საცხოვრებელი ფართი მართლაც განსაკუთრებული."
}

    return render(request, 'main/about.html', context)

def contact(request):
    context: dict[str, str] = {
        "content": "ნომერი: 555555555"
}

    return render(request, 'main/contact.html', context)

def deliever(request):
    context: dict[str, str] = {
        "content": "მიტანის სერვისი"
}

    return render(request, 'main/deliever.html', context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <!-- ფილტრები -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                ფილტრები
            </button>

            <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                    <input type="hidden" name="q" value="request.GET.q">
                    <label class="form-check-label" for="flexCheckDefault">
                        პროდუქტები აქციებზე
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">დალაგება:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                    <label class="form-check-label" for="flexRadioDefault1">
                        ნაგულისხმევი
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                    <label class="form-check-label" for="flexRadioDefault2">
                        იაფიდან ძვირამდე
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                    <label class="form-check-label" for="flexRadioDefault3">
                        ძვირიდან იაფამდე
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">მიმართეთ</button>
            </form>
        </div>
        {% for product in goods %}
            <!-- პროდუქტის ბარათი -->
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-primary rounded custom-shadow">
                    {% if product.image %}
                        <img src="{{ product.image.url  }}" class="card-img-top" alt="{{ product.name  }}">
                    {% else %}
                        <img src={% static "deps/images/Not found image.png" %} class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <a href="../goods/product.html">
                            <p class="card-title">{{ product.name }}</p>
                        </a>
                        <p class="card-text text-truncate">{{ product.description }}</p>
                        <p class="product_id">id: {{ product.display_id }}</p>
                        <div class="d-flex justify-content-between">
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> $</p>
                                <p><strong>{{ product.sell_price }} $</strong></p>
                                <span class="badge bg-warning text-dark">ფასდაკლება {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} $</strong></p>
                            {% endif %}
                            
                            <a href="#" class="btn add-to-cart">
                                <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                    width="32" height="32">
                            </a>
                        </div>
                    </div>
                </div>
            </div>   
        {% endfor %}
    </div>
    <!-- პაგირება -->
    <nav aria-label="Page navigation example">
{% endblock  %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
        </div>
    </footer>
{% endblock  %}

goods/templates/goods/product.html
{% extends "main/base.html" %}
{% load static %}

{% block content%}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- მინიატურები -->
                <div class="col-md-4">
                    <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: 002654</p>
                </div>
                <!-- სურათის გადიდება მოდალურ ფანჯარაში -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">გამოსახულება 1</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="დახურვა"></button>
                            </div>
                            <div class="modal-body">
                                <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                                    class="img-fluid" alt="გამოსახულება 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- პროდუქტის აღწერა -->
            <div class="card-body">
                <p class="card-text">ფასი: <strong>150.00 $</strong></p>
                <h5 class="card-title">ჩაის მაგიდა და სამი სკამი</h5>
                <p class="card-text">სამი სკამიანი კომპლექტი და დიზაინერი მაგიდა მისაღები ოთახისთვის
                    ოთახები.</p>
                <a href="#" class="btn btn-dark add-to-cart">კალათაში დამატება</a>
            </div>
        </div>
    </div>
{% endblock  %}

main/templates/main/about.html
{% extends "main/base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}

{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow rounded">
        <h2 class="m-2"><strong>{{ content }}</strong></h2>
        <p class="m-2">{{ text_on_page }}</p>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
        </div>
    </footer>
{% endblock %}

main/templates/main/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- footer-ის სტილი, მთავარი ფეიჯი -->
    {% block css %}
    
    {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href=" {%static "deps/css/my_footer_css.css" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                ინფორმაცია
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url "main:deliever" %}">მიტანა და გადახდა</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:contact" %}">კონტაქტი</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">ჩვენზე</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">კალათა</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="users/login.html">შესვლა</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                ჩემი პროფილი
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">კალათა</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">პირადი კაბინეტი</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">ადმინ მენიუ</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">გასვლა</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">ძიება</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- კატალოგი და კალათა გვერდზე ფიქსირებული მდებარეობით -->
            <div class="row mt-1 position-fixed z-3">
                <!-- კატალოგი -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        კატალოგი
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}                      
                            <li><a class="dropdown-item text-white" href="{% url "catalog:index" %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- კალათის ხატულა, ხსნის მოდალურ ფანჯარას -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- კალათის მოდალური ფანჯრის განლაგება -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">კალათა</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- კალათა -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">პროდუქტი</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">სულ <strong>1</strong> ღირებული ნივთ(ებ)ი</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- კალათის მარკირება დასრულდა -->
                                </div>
                                <a class="btn btn-dark" href="{% static "orders/create_order.html" %}">
                                    გადახდა
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- მოდალური ფანჯრის განლაგება დასრულდა -->
            </div>
        </div>
        <!-- კონტენტი -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- ცარიელი ბლოკი -->
                </div>
                <div class="col-lg-10">
                    <!-- კონტენტი გვერდზე -->
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    {% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

main/templates/main/contact.html
{% extends "main/base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}

{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow rounded">
        <p><strong>{{ content }}</strong></p>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
        </div>
    </footer>
{% endblock %}

main/templates/main/deliever.html
{% extends "main/base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}

{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow rounded">
        <p><strong>{{ content }}</strong></p>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
        </div>
    </footer>
{% endblock %}

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <p>{{ content }}</p>
</body>
</html>